name: Docker Build/Publish Image

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - 
        name: Checkout the code
        uses: actions/checkout@v1
      - 
        name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v1.1.1
      - 
        name: Builder instance name
        run: echo ${{ steps.buildx.outputs.name }}
      - 
        name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}


