{
 "title": "RabbitMQ board for kbudde/rabbitmq_exporter",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Exchanges",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "rabbitmq_exchanges" }
   ]
  },
  {
   "title": "Queues",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "rabbitmq_queues" }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "100 * rabbitmq_node_mem_used / rabbitmq_node_mem_limit"
    }
   ]
  },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 } },
  {
   "title": "Publish to exchange<T>",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delta(rabbitmq_exchange_messages_published_in_total[1m])) by (vhost, exchange) >= 1",
     "legendFormat": "{{exchange}} ({{vhost}})"
    }
   ]
  },
  {
   "title": "Queue message bytes",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_queue_message_bytes > 0",
     "legendFormat": "{{queue}} {{vhost}}"
    },
    {
     "expr": "sum(rabbitmq_queue_message_bytes > 0)",
     "legendFormat": "bus-.+"
    }
   ]
  },
  {
   "title": "Published out from Exchange",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(rabbitmq_exchange_messages_published_out_total[1m]) >= 1",
     "legendFormat": "{{exchange}} ({{vhost}})"
    }
   ]
  },
  {
   "title": "Queue message count",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rabbitmq_queue_messages > 0", "legendFormat": "{{queue}} {{vhost}}" },
    {
     "expr": "sum(rabbitmq_queue_messages > 0)",
     "legendFormat": "bus-.+"
    }
   ]
  },
  {
   "title": "Disk RW",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_queue_disk_reads_total > 0",
     "legendFormat": "{{queue}} {{vhost}}"
    },
    {
     "expr": "rabbitmq_queue_disk_writes_total > 0",
     "legendFormat": "{{queue}} {{vhost}}"
    }
   ]
  },
  {
   "title": "Consumers",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rabbitmq_queue_consumers) by (queue, vhost) ",
     "legendFormat": "{{queue}} ({{vhost}})"
    }
   ]
  },
  {
   "title": "Request/Response",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delta(rabbitmq_exchange_messages_published_in_total[1m])) by (vhost, exchange) >= 1",
     "legendFormat": "{{exchange}} ({{vhost}})"
    }
   ]
  }
 ]
}