name: PR

on:
  pull_request:
    branches: [ main ]

jobs:
  tests:
    name: go tests
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version-file: '**/go.mod'
    - run: go version
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
    - name: run tests
      run: |
        export GOPATH=$HOME/go
        export PATH=$PATH:$GOPATH/bin
        go test ./... -v
